version: "3.8"
services:
  gokomodo-go-production:
    container_name: ${BACKEND_CONTAINER}
    hostname: ${BACKEND_HOST}
    image: "${BACKEND_IMAGE}:${BACKEND_IMAGE_TAG}"
    restart: always
    environment:
      BACKEND_STAGE: ${BACKEND_STAGE}
    ports:
      - "3001:3001"
    networks:
      - gokomodo-environment-production

networks:
  gokomodo-environment-production:
    external: true
    name: gokomodo-environment-production
